### ISSUE TITLE
Issue with order menu

### ISSUE THREAD

**Issue by Ecofyl** [Common-Services/lapostesuivi#1]
prestashop 1.6.1.16

After installing the module I get this message when I open the order menu to display the orders:

Mauvaise requête SQL
Column 'id_carrier' in field list is ambiguous

**Comment by debuss** [comment]
You mean page **Orders > Orders** ? Or **Orders > La Poste Suivi** ?

**Comment by debuss** [comment]
Do you have a screenshot ?

**Comment by Ecofyl** [comment]
Hello

here is a screen shot with the error message  after installing the module lapostesuivi



Cordialement
Best regards
 
Christian
Webmaster Ecofyl

**Comment by debuss** [comment]
Christian,

The screenshot is missing, can you post it directly on GitHub, not by Email ?
Also, my previous question :
> You mean page Orders > Orders ? Or Orders > La Poste Suivi ?

**Comment by Ecofyl** [comment]
![capture d ecran 2018-08-03 18 14 45](https://user-images.githubusercontent.com/5708033/43688174-71caf598-98e4-11e8-8455-94afc72844ce.jpeg)

here is the screen shot
I mean page Orders > Orders

**Comment by Ecofyl** [comment]
I mean page Orders > Orders

**Comment by debuss** [comment]
No problem for me on **PS 1.6.1.16** and **PS 1.7.4.2**, also tried with our modules Colissimo and SoNice installed as they display some informations too on this page, but no issue.
Actually our module never uses the `id_carrier` in this hook (actionAdminOrdersListingFieldsModifier).

Do you have an other module that could explain the problem ?
Or maybe on override of the AdminOrders controller ?

**Comment by Ecofyl** [comment]
I have an override on the AdminOrders controller
moduke ordertrackingupdate

* Class overrider for AdminOrdersControllerCore
* @date 2016-09-03
* @version 1.1.0
* @author Thomas GIORDMAINA <thomas.giordmaina@42webstreet.com>
* @copyright 42webstreet.com
*
*/
require_once _PS_ROOT_DIR_.'/modules/ordertrackingupdate/ordertrackingupdate.php';
class AdminOrdersController extends AdminOrdersControllerCore

**Comment by delete13** [comment]
@debuss to prevent that kind of trouble, you should reference your tables and name your fields related to those references ;

Before:
```
'SELECT `id_order_carrier`
            FROM `'._DB_PREFIX_.'order_carrier`
            WHERE `id_order` = '.(int)$this->id.'
            ORDER BY `id_order_carrier` DESC'
```
After:
```
'SELECT `id_order_carrier`
            FROM `'._DB_PREFIX_.'order_carrier` oc
            WHERE oc.`id_order` = '.(int)$this->id.'
            ORDER BY oc.`id_order_carrier` DESC'
```

**Comment by Ecofyl** [comment]
please tell me where i have to change the line: Module, programme,  line in the programme

**Comment by debuss** [comment]
@delete13 Yes, it is done already in the module in the part that need it, such as the **AdminOrdersController** or the hook **adminOrdersListingFieldsModifier**.

===

@Ecofyl There are no changes to do as I believe the problem does not come from the module. I think there is just a concurrent request on the same field or table. Or another module uses the hook **adminOrdersListingFieldsModifier** to update/add something in the order list without referencing the tables as suggested by @delete13 .

All of this because the module does not check the `id_carrier` on the hook **adminOrdersListingFieldsModifier**.
It looks for the shipping number, in tables `ps_orders` or `ps_order_carrier` :

```php
/**
 * @param array $params
 */
public function actionAdminOrdersListingFieldsModifier($params)
{
    if (!isset($params['fields']['tracking_number']) || !isset($params['fields']['shipping_number'])) {
        $params['fields']['tracking_number'] = array(
            'title' => $this->l('Tracking number'),
            'align' => 'text-center',
            'class' => 'fixed-width-xs',
        );
    }

    if (isset($params['select']) && !$this->trackingNumberAlreadyInSelect($params['select'])) {
        $params['select'] = trim($params['select'], ', ').',
            IF(a.`shipping_number`, a.`shipping_number`, oc.`tracking_number`) AS `tracking_number`';
    }

    if (isset($params['join']) && !$this->trackingNumberAlreadyInJoin($params['join'])) {
        $params['join'] .= '
            LEFT JOIN `'._DB_PREFIX_.'order_carrier` oc ON (a.`id_order` = oc.`id_order`)';
    }
}
```

Maybe you can try to disable overrides and see if you still have the warning.

**Comment by Ecofyl** [comment]
I install /desinstall both modules but I always have the same issue
