### ISSUE TITLE
Nouvelle API, nouvelle version du module ? 

### ISSUE THREAD

**Issue by Navet94** [Common-Services/lapostesuivi#10]
Bonjour.

J'ai reçu un mail de la poste pour prévenir qu'une nouvelle API était disponible (https://developer.laposte.fr/products/suivi/2) et que l'ancienne serait abandonnée au 30 avril.

Va t'il y avoir une nouvelle version du module ou est ce que le module actuel est adapté (je pense notamment si l'adresse sur lequel le module envoie ses requêtes de suivi sera différente par rapport à la nouvelle API)?

Merci beaucoup pour votre module qui nous fait gagner un temps précieux sur une boutique en 1.6 et que vous l'a mettez à disposition gratuitement. 

Bonne journée.

**Comment by cbutel** [comment]
Bonjour,
j'ai eu des infos récemment et le module devrait être mis à jour très prochainement pour l'API V2

Merci d'avance au dev :-)

**Comment by Navet94** [comment]
Merci pour cette bonne nouvelle et merci au dev bien évidemment

**Comment by benoitcollier** [comment]
Je ne sais pas si vous avez vu mais la release pour la V2 du module est disponible :-)

**Comment by Navet94** [comment]
Non je n'avais pas vu, merci pour votre message.

Je vais regarder ce week-end pour l'intégrer sur mon site

Merci aux dev
