### ISSUE TITLE
No orders to track...

### ISSUE THREAD

**Issue by benoitcollier** [Common-Services/lapostesuivi#11]
Bonjour,
Je viens d'installer le module sur ma boutique mais aucune commande n'est considérée comme suivie par le module alors que j'en ai en expédiée avec un suivi sur le transporteur La poste qui est bien sélectionné. 
En mode debug, j'obtiens l'erreur suivante :
Warning: array_combine(): Both parameters should have an equal number of elements in /var/www/clients/client4/web1/web/modules/lapostesuivi/classes/LaPosteSuiviWebService.php on line 175

Il semble qu'il y ait une erreur à la récupération des données. 
Pensez vous pouvoir corriger ce problème ?

D'avance merci.

**Comment by debuss** [comment]
Bonjour Benoit,

Le module est en cours de mis à jour pour être conforme avec l'API v2 de la poste.
Lorsque la mise à jour sera disponible, votre soucis devrait être réglé.

Merci.

**Comment by benoitcollier** [comment]
Merci :-) je vais attendre alors :-)
