### ISSUE TITLE
Notice: Undefined index: PC1

### ISSUE THREAD

**Issue by benoitcollier** [Common-Services/lapostesuivi#12]
Bonjour,

J'ai mis à jour le module avec la version 2 pour la V2 de l'API La poste cela a l'air de bien fonctionner !! Merci pour votre boulot.

Néanmoins, j'ai une erreur qui est apparue dans la fiche de commande en back office cela ne semble pas impacter la mise à jour Cron, mais l'onglet La poste suivi dans la commande affiche 0 alors même que la commande est suivie :
Notice: Undefined index: PC1 in /var/www/clients/client4/web1/web/modules/lapostesuivi/classes/handlers/LaPosteSuiviHooksHandler.php on line 192

**Comment by debuss** [comment]
La dernière version du module devrait corriger le problème.
Si vous ne l'avez pas encore fait : [https://github.com/Common-Services/lapostesuivi/releases/tag/2.1.1](https://github.com/Common-Services/lapostesuivi/releases/tag/2.1.1) .
