### ISSUE TITLE
Erreur mise à jour

### ISSUE THREAD

**Issue by benoitcollier** [Common-Services/lapostesuivi#13]
Bonjour, sur la V2 la mise à jour semblait fonctionner néanmoins je rencontre un bug. 
Il semble que lors du lancement de la tache, un soucis change l'état de certaines commandes. 
En effet j'ai une commande dont l'état était passé en "Livrée" qui a été remise en Expédié au lancement suivant. 
En relancant, la commande est repassée en livrée mais une autre est repassée en expédiée....

Dans le log de lancement : 
J'obtiens l'erreur suivante sur la commande qui est repassée en expédiée par l'outil, dernière car l'outil s'arrête en effet il y avait normalement d'autres commandes suivies à traiter.
> Treating Order #296
> Shipping Number : 3X00287566855
> SUCCESS !
=> On : 15/04/2020
=> Status : DI1
=> Message : Votre courrier est déposé dans la boîte à lettres du destinataire.
> FATAL ERROR : Kernel Container is not available

Cette erreur intervient alors que lors du passage précédent cette commande avait bien été mise en Livrée par l'outil...

**Comment by debuss** [comment]
Je vous ai envoyé une mise à jour dans une autre "issue", indiquez moi si cela corrige le soucis.
Merci.
