### ISSUE TITLE
Treating Order #1

### ISSUE THREAD

**Issue by benoitcollier** [Common-Services/lapostesuivi#14]
Dans le module v2 lors de chaque exécution, l'outil teste la commande 1 alors même que celle ci ne devrait pas rentrer dans le spectre de ses commandes à traiter (2 semaines). 
De plus cela affiche une erreur systématique :
> Treating Order #1
> 400 : Votre numéro est invalide. Veuillez le ressaisir en respectant le format.

**Comment by debuss** [comment]
Corrigé dans la mise à jour : https://www.dropbox.com/s/imr1l94sxrbcob2/lapostesuivi_2.0.1alpha.zip?dl=1 .
