### ISSUE TITLE
Améliorer le tracking et erreur 429 Too Many Requests

### ISSUE THREAD

**Issue by pppplus** [Common-Services/lapostesuivi#15]
Si on a pas mal d'envois, on se retrouve rapidement avec des erreurs du type : 
429 Too Many Requests

On peut facilement diminuer drastiquement la charge sur la poste, en éliminant les commandes déjà livrées par exemple.

J'ai manuellement ajouté dans : **/classes/LaPosteSuiviWebService.php**
dans la fonction **public static function getOrdersToTrack()**
$ignoreStatut = '5'; //= mon statut Livré donc plus besoin de rechercher

et la requete sql devient
        $orders_ids = Db::getInstance()->executeS(
            'SELECT `id_order`, `shipping_number`
            FROM `'._DB_PREFIX_.'orders`
            WHERE `id_carrier` IN ('.implode(', ', array_map('intval', $carriers_ids)).')
            AND `date_add` > DATE_ADD(NOW(), INTERVAL - '.max(7, (int)$deadline).' DAY)
            AND `current_state` NOT IN ('.$ignoreStatut.')
            AND `shipping_number` IS NOT NULL
            AND `shipping_number` != ""
            ORDER BY `id_order`'
        );

Evidemment, il faudrait mettre un champ dans le formulaire de configuration, pour gérer potentiellement plusieurs statuts à ignorer.
C'est pour ma part une charge diminuée de 75% sur le site de La poste... qui comme chacun sait rame énormément.

**Comment by debuss** [comment]
En effet, je vais rajouter un onglet dans la configuration pour ajouter des filtres sur les statuts de commande, cela permettra de filtrer les différents statuts "livré" de la boutique.

**Comment by debuss** [comment]
Il y a l'option dans la dernière version du module :

![image](https://user-images.githubusercontent.com/2537607/86992162-1864c300-c1cb-11ea-9be3-6d6245132041.png)

Vous pouvez la télécharger ici : [https://github.com/Common-Services/lapostesuivi/releases/tag/2.1.1](https://github.com/Common-Services/lapostesuivi/releases/tag/2.1.1)
