### ISSUE TITLE
fonctions absentes, le module ne marche pas du tout

### ISSUE THREAD

**Issue by pppplus** [Common-Services/lapostesuivi#16]
PHP Fatal error:  Uncaught Error: Call to undefined method Shipment::seturl() in /public_html/modules/lapostesuivi/classes/api/v2/Response.php:131

Call to undefined method Response::setCode() in /public_html/modules/lapostesuivi/classes/LaPosteSuiviWebService.php:190

Une réinitialisation a supprimé les employés 1 et 2 de la boutique... au lieu de l'employé affecté au module.

**Comment by debuss** [comment]
Pouvez-vous tester avec la prochaine version du module : https://www.dropbox.com/s/q357mfqk57344br/lapostesuivi_2.0.1.zip?dl=1 ?
