### ISSUE TITLE
Bug onglet Commande->La poste suivi

### ISSUE THREAD

**Issue by likarom** [Common-Services/lapostesuivi#2]
Bonjour
Tout d'abord merci beaucoup pour ce module gratuit.
J'ai pu l'installer, le configurer et lancer la tâche Cron sans souci et tout fonctionne correctement dans la liste des commandes du backoffice... mais avant j'avais aussi accès à un récapitulatif dans Commande->La poste suivi, mais dorénavant j'ai un message d'erreur:
" Mauvaise requête SQL
Subquery returns more than 1 row" 
Ce n'est pas super grave en soit car cela fonctionne toujours mais j'aurai voulu comprendre, pourquoi...
D'avance merci
Prestashop 1.6.14, php 7

**Comment by debuss** [comment]
Bonjour,
Avez-vous une capture d'écran de ce message d'erreur ?

**Comment by likarom** [comment]
BonjourMerci pour votre réponse, je vous joins une capture d'écran.Cdlt
    Le mercredi 31 octobre 2018 à 13:09:17 UTC+1, Debusschere Alexandre <notifications@github.com> a écrit :  
 
 
Bonjour,
Avez-vous une capture d'écran de ce message d'erreur ?

**Comment by debuss** [comment]
Vous avez répondu via votre boite mail du coup je n'ai pas reçu la pièce jointe sur GitHub, pouvez-vous la poster directement dessus ?

Sinon, une mise à jour vient d'être publier (version 1.0.02) : https://github.com/Common-Services/lapostesuivi/releases .
Vous pouvez faire un essai avec et voir si cela corrige votre problème.
