### ISSUE TITLE
Configuration : l'onglet -Statuts- est vide

### ISSUE THREAD

**Issue by jori3** [Common-Services/lapostesuivi#3]
Bonjour,
Merci pour ce module,
Je rencontre un problème, je n'arrive pas à faire le mapping des statuts, l'onglet de configuration est vide.
Le reste semble fonctionner. Il n'y a pas d'erreur dans la console de Chrome.
Cordialement,
![sans titre-1](https://user-images.githubusercontent.com/45225054/48825039-6e6ec380-ed66-11e8-9aae-b6bdb91456e5.gif)

**Comment by debuss** [comment]
Bonjour,

Le module récupère les statuts de commande en fonction de la langue courante.
Est-ce que vos statuts de commandes sont bien traduis dans la langue que vous utilisez dans le back-office PrestaShop ?

Est-ce que vous avez des statuts de commande indiquant un statut "payé" et "expédié" et non "remboursé" ?

En image :
![image](https://user-images.githubusercontent.com/2537607/48830405-1efcb780-eda7-11e8-96fa-1a7690d0d1dc.png)

**Comment by jori3** [comment]
Bonjour,
Merci pour votre réponse.
Effectivement, la case "Marquer la commande associée comme payée" n'était pas coché sur les statuts "Expédiée" et "Livrée" ce qui masquait la configuration des statuts. 
Ça résout mon problème.
Cordialement,

**Comment by debuss** [comment]
Okay parfait !
