### ISSUE TITLE
security fake superadmin account

### ISSUE THREAD

**Issue by ghost** [Common-Services/lapostesuivi#4]
After installing module was automaticly added non authorized Super admin account.

**Comment by debuss** [comment]
@nataniko ,

As you can see on file `classes/LaPosteSuiviEmployee.php` which create the employee :
```php
$cron_employee->email = 'no-reply-'.(int)rand(1000, 9999).'@lapostesuivi.fr';
$cron_employee->passwd = LaPosteSuiviTools::generateRandomPassword();
```

The email is rendered randomly, as well as the password to access the account.
So there is no worries about this account, it won't be accessed by anyone.

Also, this account is necessary (with Super Admin profile) to update order status and other stuff without issues.

**Comment by ghost** [comment]
thanks, but this kind of strange approach

**Comment by debuss** [comment]
An employee is required by PrestaShop to change the order status, that is why.

Also, thanks to this employee, you can know that it is the module which changed the order status, it can be useful for debug.

**Comment by ghost** [comment]
This code should work without Superadmin account. Just FYI

```
$orderHistory = new OrderHistory();
$orderHistory->id_order = $order->id;
$orderHistory->changeIdOrderState($orderStatus, $order, true);
$orderHistory->addWithemail(true);
```
