### ISSUE TITLE
La pagination ne marche pas sur prestashop 1.7.5.

### ISSUE THREAD

**Issue by pppplus** [Common-Services/lapostesuivi#5]
On peut ouvrir la page Commandes / La Poste Suivie.

Mais dès qu'on veut aller à la page, dès qu'on clique sur une colonne pour la classer, ou dès qu'on remplit un champ pour une recherche, ça plante immédiatement.

Aucun message d'erreur, même avec le debug activé
Erreur 505

**Comment by debuss** [comment]
Bonjour,

J'ai pu reproduire le problème et le corriger.
La mise à jour est disponible ici (version 1.0.02) : https://github.com/Common-Services/lapostesuivi/releases .

Après avoir fait la mise à jour, videz bien le cache de PrestaShop et du navigateur pour charger les dernières mises à jour des scripts sur la page du module.


Merci.
