### ISSUE TITLE
Impossible d'ajouté les transporteurs lors de la config du module

### ISSUE THREAD

**Issue by Badr77** [Common-Services/lapostesuivi#6]
Bonjour, merci pour le module, 
Quand j'essaie de configurer les transporteur sur le module ils ne s'enregistrent pas

**Comment by debuss** [comment]
Bonjour,

Quel est votre version de PrestaShop ?
Refaite des essais en vidant les caches PrestaShop et du navigateur au cas où,

**Comment by debuss** [comment]
Bonjour,

J'ai pu reproduire le problème et le corriger.
La mise à jour est disponible ici (version 1.0.02) : https://github.com/Common-Services/lapostesuivi/releases .

Après avoir fait la mise à jour, videz bien le cache de PrestaShop et du navigateur pour charger les dernières mises à jour des scripts sur la page de configuration.


Merci.

**Comment by Badr77** [comment]
Bonjour,
Ça ne marche toujours pas, 
Prestashop : 1.7.4.2
Google chrome : Version 75.0.3770.80

utilisez vous le javascript pour enregistrer les transporteur ?

**Comment by debuss** [comment]
Bonjour,

Oui il y a dans le code JavaScript une ligne qui permet de bien sélectionner les transporteurs avant enregistrement.
Désactivez le cache temporairement pour être sûr que ce soit chargé.

**Comment by Badr77** [comment]
Bonjour, 
J'ai mis mon java script dans le footer, donc je pense que le module demande des librairies qui ne sont appelé que plus tard dans la page et du coup n'enregistre pas les transporteur sélectionnés

**Comment by Badr77** [comment]
Même en remettant le javascript dans head.tpl, ça ne fonctionne pas ,
Du coup j'aimerai savoir les ligne de code à modifier pour pouvoir les rentrer en dur dans le code,
pour corriger au moins temporairement le soucis

**Comment by debuss** [comment]
Dans le fichier `views/js/back.js`.
À la fin du fichier :
```javascript
// Before submitting form :
//    * Select selected status and carriers
$('button[name="submitLaPosteSuiviModule"]').click(function () {
    $('.selectedStatus, .selectedSwap').find('option').attr('selected', true);
});
```

En relisant la ligne, je pense avoir trouvé le soucis cependant, vous pouvez tester en modifiant comme ceci :
```javascript
// Before submitting form :
//    * Select selected status and carriers
$('#module_form').submit(function () {
    $('.selectedStatus, .selectedSwap').find('option').attr('selected', true);

    return true;
});
```

**Comment by Badr77** [comment]
d'accord merci , je vais tester ça vous êtes hyper efficace en tout cas

**Comment by debuss** [comment]
Merci !
Si le problème est bien réglé, indiquez le moi comme ça je mettrais en place une nouvelle version.

**Comment by Badr77** [comment]
Non ça ne fonctionne toujours pas

**Comment by debuss** [comment]
Le cache JavaScript est bien vidé ?

**Comment by Badr77** [comment]
Oui j'ai tout vidé sur le site et dans le navigateur

**Comment by debuss** [comment]
Une mise à jour est disponible, pouvez-vous faire un essai avec : https://github.com/Common-Services/lapostesuivi/releases ?

**Comment by Badr77** [comment]
Dac je regarde ça et je vous tiens au courant

**Comment by Badr77** [comment]
Alors ça ne m'affiche les transporteur pas comme choisi mais ça agis bien sur les livraison

**Comment by debuss** [comment]
Que voulez-vous dire ?
Pouvez-vous me donner plus de détails ?

**Comment by Badr77** [comment]
le tableau des transporteur sélectionné reste vide mais
qd je lance la tache cron les livraison sont bien suivi

**Comment by debuss** [comment]
Est-ce que vous êtes en multi-boutique ?
Il y a une mise à jour disponible, vous pouvez l'essayer au cas où : https://github.com/Common-Services/lapostesuivi/releases/tag/1.0.04 .

**Comment by debuss** [comment]
@Badr77 
Est-ce que le soucis est résolu avec la mise à jour ?
Si non, pouvez-vous m'indiquer votre navigateur ?
