### ISSUE TITLE
Problème de commande qui ne passe pas en livré

### ISSUE THREAD

**Issue by Tiruve** [Common-Services/lapostesuivi#7]
Bonjour,

Nous remarquons un problème lors de l'exécution de la tache cron.
Nous avons l'impression que lorsque nous exécutons la tâche, celle-ci ne prend pas toutes les commandes (par exemple je viens de faire l'essai 5 fois en lançant l'url à la main, et sur tout mes F5, la page m'affiche uniquement 5 commandes, à chaque fois les mêmes).

Une correction possible ? Un bug sur notre site ?

**Comment by debuss** [comment]
Bonjour,

Non pas de soucis, la tache cron récupère toutes les commandes dans l'intervalle de temps que vous avez défini dans la configuration du module (Paramètres > Suivre les commandes jusqu'à) à chaque appel.
Donc il est normal que vous récupériez les mêmes commandes à chaque fois.

=====

> Nous avons l'impression que lorsque nous exécutons la tâche, celle-ci ne prend pas toutes les commandes 

Est-ce que tous les transporteurs (compatibles) sont sélectionnées ?
Est-ce que la plage de date est assez grande (Paramètres > Suivre les commandes jusqu'à) ?

**Comment by Tiruve** [comment]
![image](https://user-images.githubusercontent.com/19334307/59103722-f21d8580-892f-11e9-9d3b-582b40d289f7.png)
![image](https://user-images.githubusercontent.com/19334307/59103741-fba6ed80-892f-11e9-8ff2-1903ca3abaae.png)
Voici les screens de la config,
Dans la logique des choses, la tache cron devrait récupérer plus d'une centaine de commande au minimum.
Mais elle nous en sort que 5. :/

**Comment by debuss** [comment]
Si vous passez l'option à 4 ou 5 semaines, est-ce mieux ?
Est-ce que les commandes ont un numéro de suivi ?

**Comment by Tiruve** [comment]
Toujours pareil à 4 semaines.
Les commandes ont un numéro de suivi.

La tache cron passe sur les commandes entre l'ID 136968 & l'ID 136999
Sachant que la 136968 a été passée aujourd'hui,
et que la commande 136964 a été passée aujourd'hui, a aussi un numéro de suivi, mais n'est pas prise en compte par la tache cron.

**Comment by debuss** [comment]
Okay, je ne vois pas trop qu'elle pourrait être le soucis, la requête SQL pour récupérer les commandes est plutôt simple, cela ne devrait pas vraiment poser de problème.
Afin de voir cela plus en détails, pouvez-vous me contacter sur ce mail : alexandre@common-services.com ?

Merci.

**Comment by pppplus** [comment]
Lorsqu'il y a bcp de commandes (plus de 25), ça ne prend que le dernier tableau après array_chunk
154        $code_chunks = array_chunk($codes, 25, true);
(fichier LaPosteSuiviWebService.php)

Je ne vois pas pourquoi pour l'instant. L'enchainement des actions ne me parait pas clair

C'est le seul dernier tableau qui est traité dans tracking.php

Si on passe à : 
$code_chunks = array_chunk($codes, 5000, true);
(donc pour moi, un seul tableau, j'ai moins de 5000 commandes :-)) ça traite bien correctement.

La fonction CallMultiple est à revoir.

**Comment by debuss** [comment]
Je vois d'où vient le soucis, en effet toutes les commandes étaient suivi, mais uniquement les 25 dernières commandes étaient traitées.
J'ai corrigé et posté une nouvelle mise à jour du module : https://github.com/Common-Services/lapostesuivi/releases .

**Comment by Tiruve** [comment]
Merci, la nouvelle version fonctionne avec 2 semaines de délais!

En revanche, lorsqu'on met 4 semaines de délais cela ne fonctionne plus (le message "No orders to track..." apparaît)
Ça ne pose pas de problème pour l'instant vu que nous utilisons 2 semaines, c'est juste pour vous informer ;)

**Comment by debuss** [comment]
Okay super si c'est mieux !
Pour les 4 semaines, possibles que ce soit à cause du fait que les commandes ont été suivi il n'y a pas longtemps.
À vérifier dans quelques heures si ça se reproduit.

**Comment by pppplus** [comment]
PS : j'ai posté déjà 2 fois une modif car il y a un problème avec PS 1.7 et c'est effacé à chaque fois.

/controllers/admin/AdminOrdersLaPosteSuiviController.php
    public function setMedia()
    {
        parent::setMedia();
        $this->addCSS($this->module->folder_path.'/views/css/controller.css');
    }

Ce n'est plus valide ! Il faut écrire 

    public function setMedia($isNewTheme = false)
    {
        parent::setMedia($isNewTheme);

        $this->addCSS($this->module->folder_path.'/views/css/controller.css');
    }

**Comment by debuss** [comment]
Je viens de mettre en ligne une nouvelle version du module avec la correction : https://github.com/Common-Services/lapostesuivi/releases/tag/1.0.04 .

**Comment by Tiruve** [comment]
Salut @debuss ! 
Toujours un problème de "No orders to track", mais maintenant même à une semaine de délai.
Sachant qu'on a 1100 commandes sur cette dernière semaine, est-ce un problème de trop grand nombre de commande ? Sais-tu corriger ce problème ?

**Comment by debuss** [comment]
Bonjour @Tiruve ,
Est-ce que vos transporteurs sont sélectionnés dans la configuration.
Si vous regardez dans la Db, table `ps_configuration`, sont-ils listés sur la ligne avec la colonne "name" égale à "LPS_SELECTED_CARRIERS" ?

**Comment by Tiruve** [comment]
Bonjour @debuss 
Yes les transporteurs sont bien sélectionnés, et dans la base les IDs sont bien listé dans LPS_SELECTED_CARRIERS,
On remarque que lorsque nous retirons le transporteur Mon Domicile, le suivi fonctionne. Donc j'imagine que c'est bien du à un trop grand nombre de commandes à suivre.

**Comment by debuss** [comment]
Si vous activez le mode DEV de PrestaShop (dans **Paramètres Avancés > Performances**), est-ce que vous recevez un message d'erreur lorsque vous exécutez la tache planifiée ?
