### ISSUE TITLE
Problème rencontré avec module Amazon

### ISSUE THREAD

**Issue by sebastienlett** [Common-Services/lapostesuivi#8]
Bonjour,
Sur PS 1.7.6.1, nous utilisons le module Amazon v4.4.134 également développé par Common-Services.
Il s'avère qu'il y a une incompatibilité entre les 2 modules "amazon" et "lapostesuivi"". 
Erreur en mode debug :> FATAL ERROR : No orders to track.
Or il y a bien des commandes à traiter.
Cordialement,
S LETT

**Comment by debuss** [comment]
Il ne s'agit pas d'une incompatibilité, juste il n'y a pas de commande à suivre...
Les transporteurs des commandes Amazon sont bien sélectionnés dans la configuration du module La Poste Suivi ?
Les commandes sont dans le bon statut de commande ? Avec un numéro de suivi ?
