### ISSUE TITLE
FATAL ERROR : Kernel Container is not available

### ISSUE THREAD

**Issue by jeeece** [Common-Services/lapostesuivi#9]
Bonjour,

Je rencontre une erreur lors de la mise à jour des suivi pour des envoi La Poste courrier Suivi. J'ai regardé du côté de la tâche cron et c'est là que ça bug puisque à la première mise à jour de statut d'un nouvel envoi, la première ligne passe normalement mais les suivantes ne se font pas car il y a une erreur : FATAL ERROR : Kernel Container is not available
En actualisant la tâche, la mise à jour se fait pour l'envoi suivant puis de nouveau une erreur sur le suivant et ainsi de suite jusqu'à que tout soit enregistré. Une fois que le colis est en statut "PRIS_EN_CHARGE" il n'y a plus d'erreur et le suivi se fait normalement.

**Comment by benoitcollier** [comment]
Je rencontre ce soucis sur la nouvelle version v2 du module > FATAL ERROR : Kernel Container is not available

**Comment by debuss** [comment]
Pouvez-vous faire un essai avec la mise à jour : https://www.dropbox.com/s/imr1l94sxrbcob2/lapostesuivi_2.0.1alpha.zip?dl=1 ?
Merci.
